version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused

  settings:
    staticcheck:
      checks:
        - all
        - -SA1019  # Ignore deprecation warnings (pubsub v1)
        - -QF1008  # Ignore embedded field selector suggestions
        - -ST1000  # Package comments
        - -ST1003  # Naming conventions (Api vs API) - changing would break CRDs
        - -ST1020  # Comment format on exported functions
        - -ST1021  # Comment format on exported types

  exclusions:
    rules:
      # Ignore unchecked Close in defer statements
      - linters:
          - errcheck
        source: "defer .+\\.Close\\(\\)"
      # Ignore os.Setenv in tests
      - linters:
          - errcheck
        path: _test\.go
        source: "os\\.Setenv"
