---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-unleash-nais-io-v1-unleash
  failurePolicy: Fail
  name: munleash.kb.io
  rules:
  - apiGroups:
    - unleash.nais.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - unleashes
  sideEffects: None
