
# Prometheus Alertmanager configuration
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    control-plane: controller-manager
    app.kubernets.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: unleasherator
    app.kubernetes.io/part-of: unleasherator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-alerts
  namespace: system
spec:
  groups:
  - name: unleasherator
    rules:
    - alert: ReconciliationFailure
      expr: sum_over_time(controller_runtime_reconcile_errors_total{namespace="crossplane-system", controller="managed/cloudsqlinstance.database.gcp.crossplane.io"}[5m]) > 20
      for: 5m
      labels:
        severity: page
      annotations:
        summary: '{{ $labels.controller }} reconciliation has been failing for more than 20 time in the last 5 minutes.'