# permissions for end users to view apitokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apitoken-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/part-of: controller-manager
    app.kubernetes.io/managed-by: kustomize
  name: apitoken-viewer-role
rules:
- apiGroups:
  - unleash.nais.io
  resources:
  - apitokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unleash.nais.io
  resources:
  - apitokens/status
  verbs:
  - get
