apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: unleasherator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: unleasherator
    app.kubernetes.io/part-of: unleasherator
    app.kubernetes.io/managed-by: kustomize
  name: unleasherator
  namespace: system
