# permissions for end users to view unleashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: unleash-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: unleasherator
    app.kubernetes.io/created-by: unleasherator
    app.kubernetes.io/managed-by: kustomize
  name: unleash-viewer-role
rules:
- apiGroups:
  - unleash.nais.io
  resources:
  - unleashes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unleash.nais.io
  resources:
  - unleashes/status
  verbs:
  - get
