// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.26.1
// source: internal/pb/unleasherator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Unknown     Status = 0
	Status_Provisioned Status = 1
	Status_Removed     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "Provisioned",
		2: "Removed",
	}
	Status_value = map[string]int32{
		"Unknown":     0,
		"Provisioned": 1,
		"Removed":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_unleasherator_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_pb_unleasherator_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_unleasherator_proto_rawDescGZIP(), []int{0}
}

type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// v1
	Version       int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        Status   `protobuf:"varint,2,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	Name          string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	SecretToken   string   `protobuf:"bytes,5,opt,name=secretToken,proto3" json:"secretToken,omitempty"`
	Namespaces    []string `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Clusters      []string `protobuf:"bytes,7,rep,name=clusters,proto3" json:"clusters,omitempty"`
	SecretNonce   string   `protobuf:"bytes,8,opt,name=secretNonce,proto3" json:"secretNonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_internal_pb_unleasherator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_unleasherator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_internal_pb_unleasherator_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Instance) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Instance) GetSecretToken() string {
	if x != nil {
		return x.SecretToken
	}
	return ""
}

func (x *Instance) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Instance) GetClusters() []string {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *Instance) GetSecretNonce() string {
	if x != nil {
		return x.SecretNonce
	}
	return ""
}

var File_internal_pb_unleasherator_proto protoreflect.FileDescriptor

var file_internal_pb_unleasherator_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x6e,
	0x6c, 0x65, 0x61, 0x73, 0x68, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xee, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x2a, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x69, 0x73, 0x2f, 0x75,
	0x6e, 0x6c, 0x65, 0x61, 0x73, 0x68, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_pb_unleasherator_proto_rawDescOnce sync.Once
	file_internal_pb_unleasherator_proto_rawDescData []byte
)

func file_internal_pb_unleasherator_proto_rawDescGZIP() []byte {
	file_internal_pb_unleasherator_proto_rawDescOnce.Do(func() {
		file_internal_pb_unleasherator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_unleasherator_proto_rawDesc), len(file_internal_pb_unleasherator_proto_rawDesc)))
	})
	return file_internal_pb_unleasherator_proto_rawDescData
}

var file_internal_pb_unleasherator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_unleasherator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_unleasherator_proto_goTypes = []any{
	(Status)(0),      // 0: pb.Status
	(*Instance)(nil), // 1: pb.Instance
}
var file_internal_pb_unleasherator_proto_depIdxs = []int32{
	0, // 0: pb.Instance.status:type_name -> pb.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_unleasherator_proto_init() }
func file_internal_pb_unleasherator_proto_init() {
	if File_internal_pb_unleasherator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_unleasherator_proto_rawDesc), len(file_internal_pb_unleasherator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_unleasherator_proto_goTypes,
		DependencyIndexes: file_internal_pb_unleasherator_proto_depIdxs,
		EnumInfos:         file_internal_pb_unleasherator_proto_enumTypes,
		MessageInfos:      file_internal_pb_unleasherator_proto_msgTypes,
	}.Build()
	File_internal_pb_unleasherator_proto = out.File
	file_internal_pb_unleasherator_proto_goTypes = nil
	file_internal_pb_unleasherator_proto_depIdxs = nil
}
