// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.26.1
// source: internal/pb/unleasherator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Unknown     Status = 0
	Status_Provisioned Status = 1
	Status_Removed     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "Provisioned",
		2: "Removed",
	}
	Status_value = map[string]int32{
		"Unknown":     0,
		"Provisioned": 1,
		"Removed":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_unleasherator_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_pb_unleasherator_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_unleasherator_proto_rawDescGZIP(), []int{0}
}

type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// v1
	Version       int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        Status   `protobuf:"varint,2,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	Name          string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	SecretToken   string   `protobuf:"bytes,5,opt,name=secretToken,proto3" json:"secretToken,omitempty"`
	Namespaces    []string `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Clusters      []string `protobuf:"bytes,7,rep,name=clusters,proto3" json:"clusters,omitempty"`
	SecretNonce   string   `protobuf:"bytes,8,opt,name=secretNonce,proto3" json:"secretNonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_internal_pb_unleasherator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_unleasherator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_internal_pb_unleasherator_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Instance) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Instance) GetSecretToken() string {
	if x != nil {
		return x.SecretToken
	}
	return ""
}

func (x *Instance) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Instance) GetClusters() []string {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *Instance) GetSecretNonce() string {
	if x != nil {
		return x.SecretNonce
	}
	return ""
}

var File_internal_pb_unleasherator_proto protoreflect.FileDescriptor

const file_internal_pb_unleasherator_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/pb/unleasherator.proto\x12\x02pb\"\xee\x01\n" +
	"\bInstance\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\"\n" +
	"\x06status\x18\x02 \x01(\x0e2\n" +
	".pb.StatusR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vsecretToken\x18\x05 \x01(\tR\vsecretToken\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x06 \x03(\tR\n" +
	"namespaces\x12\x1a\n" +
	"\bclusters\x18\a \x03(\tR\bclusters\x12 \n" +
	"\vsecretNonce\x18\b \x01(\tR\vsecretNonce*3\n" +
	"\x06Status\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vProvisioned\x10\x01\x12\v\n" +
	"\aRemoved\x10\x02B&Z$github.com/nais/unleasherator/pkg/pbb\x06proto3"

var (
	file_internal_pb_unleasherator_proto_rawDescOnce sync.Once
	file_internal_pb_unleasherator_proto_rawDescData []byte
)

func file_internal_pb_unleasherator_proto_rawDescGZIP() []byte {
	file_internal_pb_unleasherator_proto_rawDescOnce.Do(func() {
		file_internal_pb_unleasherator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_unleasherator_proto_rawDesc), len(file_internal_pb_unleasherator_proto_rawDesc)))
	})
	return file_internal_pb_unleasherator_proto_rawDescData
}

var file_internal_pb_unleasherator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pb_unleasherator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_unleasherator_proto_goTypes = []any{
	(Status)(0),      // 0: pb.Status
	(*Instance)(nil), // 1: pb.Instance
}
var file_internal_pb_unleasherator_proto_depIdxs = []int32{
	0, // 0: pb.Instance.status:type_name -> pb.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_unleasherator_proto_init() }
func file_internal_pb_unleasherator_proto_init() {
	if File_internal_pb_unleasherator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_unleasherator_proto_rawDesc), len(file_internal_pb_unleasherator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_unleasherator_proto_goTypes,
		DependencyIndexes: file_internal_pb_unleasherator_proto_depIdxs,
		EnumInfos:         file_internal_pb_unleasherator_proto_enumTypes,
		MessageInfos:      file_internal_pb_unleasherator_proto_msgTypes,
	}.Build()
	File_internal_pb_unleasherator_proto = out.File
	file_internal_pb_unleasherator_proto_goTypes = nil
	file_internal_pb_unleasherator_proto_depIdxs = nil
}
