apiVersion: unleash.nais.io/v1
kind: ReleaseChannel
metadata:
  labels:
    app.kubernetes.io/name: unleasherator
    app.kubernetes.io/managed-by: kustomize
  name: releasechannel-sample
spec:
  # Docker image for this release channel
  image: "unleashorg/unleash-server:5.7.0"

  # Advanced strategy configuration (planned features)
  # strategy:
  #   maxParallel: 2
  #   batchInterval: "30s"
  #   canary:
  #     enabled: true
  #     podSelector:
  #       matchLabels:
  #         deployment: "canary"

  # Health check configuration (planned feature)
  # healthChecks:
  #   enabled: true
  #   initialDelay: "30s"
  #   timeout: "5m"

  # Rollback configuration (planned feature)
  # rollback:
  #   enabled: true
  #   onFailure: true
---
# Example Unleash instance that will be managed by the release channel
apiVersion: unleash.nais.io/v1
kind: Unleash
metadata:
  name: unleash-production
  labels:
    deployment: "production"
spec:
  database:
    url: "postgres://unleash-db:5432/unleash"
  # This connects the Unleash instance to the release channel
  releaseChannel:
    name: releasechannel-sample
---
# Example second Unleash instance for testing rollouts
apiVersion: unleash.nais.io/v1
kind: Unleash
metadata:
  name: unleash-staging
  labels:
    deployment: "staging"
spec:
  database:
    url: "postgres://unleash-db:5432/unleash"
  # This connects the Unleash instance to the release channel
  releaseChannel:
    name: releasechannel-sample
