apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  labels:
    app.kubernetes.io/name: apitoken
    app.kubernetes.io/instance: apitoken-sample
    app.kubernetes.io/part-of: unleasherator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: unleasherator
  name: apitoken-sample
spec:
  unleasshInstance:
    apiVersion: unleash.nais.io/v1
    kind: Unleash
    name: unleash-sample
  secretName: apitoken-sample
  type: CLIENT
  environment: development
  projects:
    - my-project
    - my-other-project