{{- if and .Values.networkPolicy .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.apiServerCIDR | required "networkPolicy.apiServerCIDR is required" }}
  {{- if .Values.networkPolicy.extraOutboundIPs }}
  {{- range .Values.networkPolicy.extraOutboundIPs }}
    - ipBlock:
        cidr: {{ . }}/32
  {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.allowDNS }}
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  {{- end }}
  {{- if and .Values.networkPolicy.grafanaTempo .Values.networkPolicy.grafanaTempo.enabled }}
  - to:
    - namespaceSelector:
        kubernetes.io/metadata.name: {{ .Values.networkPolicy.grafanaTempo.namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/component: distributor
          app.kubernetes.io/instance: tempo
          app.kubernetes.io/name: tempo
    ports:
      - port: 4317
        protocol: TCP
  {{- end }}
  {{- if .Values.networkPolicy.allowAllNamespaces }}
  - to:
    - namespaceSelector: {}
  {{- else }}
  {{- range .Values.networkPolicy.allowedNamespaces }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ . }}
  {{- end }}
  {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-loadbalancer-egress
spec:
  egress:
  - to:
    - podSelector: {}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: bifrost-unleash
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: loadbalancer-iap
  policyTypes:
  - Egress
{{- end }}
