{
 "title": "Unleash Instance Metrics",
 "tags": [
  "nais-frontend",
  "unleash"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(feature_toggles_total, namespace)"
    }
   },
   {
    "name": "job",
    "label": "instans",
    "query": {
     "query": "label_values(feature_toggles_total, job)"
    }
   },
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  { "title": "Unleash Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unleash Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(feature_toggles_total{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feature Toggles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feature_toggles_total{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activation Strategies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strategies_total{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contexts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(context_total{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(segments_total{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Active Users last 30 days",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(users_active_30{job=~\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Apps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(client_apps_total{job=~\"$job\", namespace=\"$namespace\", range=\"allTime\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Database Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "db_pool_free{job=~\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "free - {{service}}"
    },
    {
     "expr": "db_pool_used{job=~\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "used - {{service}}"
    },
    {
     "expr": "db_pool_max{job=~\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "max - {{service}}"
    },
    {
     "expr": "db_pool_min{job=~\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "min - {{service}}"
    }
   ]
  },
  {
   "title": "Query Latency for $quantile quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(db_query_duration_seconds{quantile=\"$quantile\", job=~\"$job\", namespace=\"$namespace\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_milliseconds_count{job=~\"$job\", namespace=\"$namespace\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Response Latency $quantile quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_milliseconds{quantile=\"$quantile\", job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])) by (quantile, job)",
     "legendFormat": "{{job}} - App P$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{service=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])) by (le, service))*100",
     "legendFormat": "{{service}} - LB P$quantile"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n    sum(\n        rate(http_request_duration_milliseconds_count{job=~\"$job\", status=~\"5..\"}[5m])\n    ) by (job) or 0 / sum(\n        rate(http_request_duration_milliseconds_count{job=~\"$job\"}[5m])\n    ) by (job) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", namespace=\"$namespace\"}[2m]) * 100",
     "legendFormat": "User CPU - {{service}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", namespace=~\"$namespace\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{service}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=\"bifrost-unleash\", container!=\"sql-proxy\", pod=~\"$job-.*\"}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{job=~\"$job\", namespace=~\"$namespace\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=~\"$job\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Process Memory - {{service}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Heap Total - {{service}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{service}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "External Memory - {{service}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Active Handler - {{service}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Active Request - {{service}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Heap Total - {{service}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{service}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "Heap Used - {{service}} - {{space}}"
    }
   ]
  }
 ]
}