---
controllerManager:
  manager:
    imagePullPolicy: Never
controllerManagerGcp:
  serviceAccountCredentialsJson: "{}"
networkPolicy:
  enabled: true
  apiServerCIDR: 10.43.0.1/32
  allowDNS: true
  allowedNamespaces:
    - unleasherator-system
    - foo
    - bar
  extraOutboundIPs:
    - 1.2.3.4
    - 4.5.6.7
  otlpServiceEndpoint:
  - to:
    - namespaceSelector:
        matchLabels:
          "kubernetes.io/metadata.name": nais-system
      podSelector:
        matchLabels:
          "app.kubernetes.io/component": distributor
          "app.kubernetes.io/instance": tempo
          "app.kubernetes.io/name": tempo
    ports:
      - port: 4317
        protocol: TCP
