name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install make
        run: sudo apt-get update && sudo apt-get install make
      - name: Lint code
        run: |
          make fmt
          if git diff-index --quiet HEAD --; then
            echo "Code formatted successfully."
          else
            echo "Code has formatting issues."
            exit 1
          fi
      - name: Vet code
        run: make vet
      - name: Test code
        run: make test
      - name: Build binary
        run: make build
