name: Dependabot auto-merge
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # ratchet:dependabot/fetch-metadata@v3.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # ratchet:actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPENDABOT_AUTO_MERGE_APP_ID}}
          private-key: ${{ secrets.DEPENDABOT_AUTO_MERGE_APP_SECRET }}

      - name: Authenticate cli
        run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
