name: Fasit Deploy
on:
  workflow_run:
    workflows: ["Helm Chart", "Container Image"]
    branches: [main]
    types:
      - completed
env:
  ARTIFACT_REGISTRY: europe-north1-docker.pkg.dev
  ARTIFACT_REPO: nais-io/nais/feature

jobs:
  meta:
    name: Metadata
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      name: ${{ steps.name.outputs.name }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: echo "version=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}
      - id: name

        run: echo "name=${{ github.event.repository.name }}" >> ${GITHUB_OUTPUT}
  wait:
    name: Wait for workflows
    permissions:
      actions: read
    runs-on: ubuntu-latest
    needs: meta
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@2aa3d9e1a12ecaaa9908e368eaf2123bb084323e
  deploy-crds:
    name: Deploy CRDs to Fasit
    runs-on: fasit-deploy

    permissions:
      id-token: write
    needs: [meta, wait]
    steps:
      - name: Deploy CRDs
        uses: nais/fasit-deploy@53e433b1bdd08fc622e03a78584c0832c9083bd3 # ratchet:nais/fasit-deploy@v4.1.1
        with:
          chart: oci://${{ env.ARTIFACT_REGISTRY }}/${{ env.ARTIFACT_REPO }}/${{ needs.meta.outputs.name }}-crds
          version: ${{ needs.meta.outputs.version }}
          targets: |
            [
              { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "onprem", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "management" } },
              { "target": { "kind": "tenant" } },
              { "target": { "kind": "onprem" } }
            ]
  deploy-controller:
    name: Deploy Controller to Fasit
    runs-on: fasit-deploy

    permissions:
      id-token: write
    needs: [meta, deploy-crds]
    steps:
      - name: Deploy Operator
        uses: nais/fasit-deploy@53e433b1bdd08fc622e03a78584c0832c9083bd3 # ratchet:nais/fasit-deploy@v4.1.1
        with:
          chart: oci://${{ env.ARTIFACT_REGISTRY }}/${{ env.ARTIFACT_REPO }}/${{ needs.meta.outputs.name }}
          version: ${{ needs.meta.outputs.version }}
          targets: |
            [
              { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "onprem", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "management" } },
              { "target": { "kind": "tenant" } },
              { "target": { "kind": "onprem" } }
            ]
  git-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [meta, deploy-controller]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v4
      - name: git tag and push
        run: |-
          git tag ${{ needs.meta.outputs.version }}
          git push origin ${{ needs.meta.outputs.version }}


